Replace .eslintrc.json with .eslintrc.js
And include updates from the Vue template project (the result of running
`npm init vue@latest`).

This fixes eslint throwing an error:

	Parsing error: Cannot find module '@typescript-eslint/parser'